[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lints.clippy]
pedantic = "deny"
absolute_paths = "deny"
# unwrap_used = "warn"
unwrap_used = "deny"
expect_used = "deny"